name: Build Extension

on:
  push:
    branches:
      - '*'

jobs:
  build-mainnet:
    runs-on: ubuntu-latest
    env:
      HORIZON_NETWORK: mainnet
      TARGET_BROWSER: chromium
      HORIZON_IS_EXTENSION: true
      HORIZON_COUNTERPARTY_API_BASE: "https://api.unspendablelabs.com:4000/v2"
      HORIZON_ANALYTICS_ENABLED: "true"
      HORIZON_POSTHOG_API_KEY: ${{ secrets.POSTHOG_API_KEY }}
      HORIZON_POSTHOG_API_HOST: "https://us.i.posthog.com"
      HORIZON_SENTRY_ENABLED: "false"
      HORIZON_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      HORIZON_SENTRY_SAMPLE_RATE: "0.5"

    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.2
      - run: flutter pub get
      
      - name: Build Extension
        run: |
          dart tool/build_extension.dart

      - name: Upload Extension
        uses: actions/upload-artifact@v4
        with:
          name: mainnet-extension.zip
          path: build/web

  build-testnet4:
    runs-on: ubuntu-latest
    env:
      HORIZON_NETWORK: testnet4
      TARGET_BROWSER: chromium
      HORIZON_IS_EXTENSION: true
      
    steps:
      - uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.29.2
      - run: flutter pub get

      - name: Build Extension
        run: |
          dart tool/build_extension.dart

      - name: Upload Extension
        uses: actions/upload-artifact@v4
        with:
          name: testnet4-extension.zip
          path: build/web
